// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3GugaoJde4oK5L0zoCWcTaxekERJ-5D4',
    appId: '1:804258373122:web:c7c0c5ae824e7ada1e111b',
    messagingSenderId: '804258373122',
    projectId: 'teacher-7f249',
    authDomain: 'teacher-7f249.firebaseapp.com',
    storageBucket: 'teacher-7f249.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc03opfxtcGtjrJ60i0OeCXRPLvoWVeG8',
    appId: '1:804258373122:android:38b42bb330cfd2d01e111b',
    messagingSenderId: '804258373122',
    projectId: 'teacher-7f249',
    storageBucket: 'teacher-7f249.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaQq0QSwiWHhZA0VZB-Cyzl4lkoF37XKo',
    appId: '1:804258373122:ios:6c81b5b29da67d191e111b',
    messagingSenderId: '804258373122',
    projectId: 'teacher-7f249',
    storageBucket: 'teacher-7f249.firebasestorage.app',
    iosClientId: '804258373122-q4mvpan7r5dd6hlot3bijihmc7ecsdti.apps.googleusercontent.com',
    iosBundleId: 'com.m.flutterwallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaQq0QSwiWHhZA0VZB-Cyzl4lkoF37XKo',
    appId: '1:804258373122:ios:6c81b5b29da67d191e111b',
    messagingSenderId: '804258373122',
    projectId: 'teacher-7f249',
    storageBucket: 'teacher-7f249.firebasestorage.app',
    iosClientId: '804258373122-q4mvpan7r5dd6hlot3bijihmc7ecsdti.apps.googleusercontent.com',
    iosBundleId: 'com.m.flutterwallet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3GugaoJde4oK5L0zoCWcTaxekERJ-5D4',
    appId: '1:804258373122:web:576657cf153cca231e111b',
    messagingSenderId: '804258373122',
    projectId: 'teacher-7f249',
    authDomain: 'teacher-7f249.firebaseapp.com',
    storageBucket: 'teacher-7f249.firebasestorage.app',
  );
}
